name: run push images

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: run sync images
        run: chmod +x ./main && ./main -v 2
